### ISSUE TITLE
Error when trying to use /domain/query

### ISSUE THREAD

**Issue by freethewhat** [Montana-Code-School/tago#23]
Attempting to do a GET request on http://localhost:3001/api/domain/query/TestArea I recieve an error in the terminal. 

``` 
 CastError: Cast to number failed for value "TestArea" at path "dateCreated"
    at CastError (/Users/matthewsutton/code/tago/backend/dist/server.js:16270:11)
    at SchemaNumber.cast (/Users/matthewsutton/code/tago/backend/dist/server.js:36520:9)
    at SchemaNumber.SchemaType._castForQuery (/Users/matthewsutton/code/tago/backend/dist/server.js:7270:15)
    at SchemaNumber.castForQuery (/Users/matthewsutton/code/tago/backend/dist/server.js:36571:14)
    at SchemaNumber.SchemaType.castForQueryWrapper (/Users/matthewsutton/code/tago/backend/dist/server.js:7227:15)
    at cast (/Users/matthewsutton/code/tago/backend/dist/server.js:31870:32)
    at cast (/Users/matthewsutton/code/tago/backend/dist/server.js:31645:18)
    at model.Query.Query.cast (/Users/matthewsutton/code/tago/backend/dist/server.js:35312:12)
    at model.Query.Query._castConditions (/Users/matthewsutton/code/tago/backend/dist/server.js:33307:10)
    at model.Query.Query._find (/Users/matthewsutton/code/tago/backend/dist/server.js:33322:8)
    at /Users/matthewsutton/code/tago/backend/dist/server.js:76651:8
    at /Users/matthewsutton/code/tago/backend/dist/server.js:76424:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Cast to number failed for value "TestArea" at path "dateCreated" for model "Domain"',
  name: 'CastError',
  stringValue: '"TestArea"',
  kind: 'number',
  value: 'TestArea',
  path: 'dateCreated',
  reason: undefined,
  model:
   { [Function: model]
     hooks: Kareem { _pres: {}, _posts: {} },
     base:
      Mongoose {
        connections: [Array],
        models: [Object],
        modelSchemas: [Object],
        options: [Object],
        plugins: [Array] },
     modelName: 'Domain',
     model: [Function: model],
     db:
      NativeConnection {
        base: [Object],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        hosts: null,
        host: 'ds113826.mlab.com',
        port: 13826,
        user: 'Keesha',
        pass: 'skool16',
        name: 'tago',
        options: null,
        otherDbs: [],
        states: [Object],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        _listening: false,
        _connectionOptions: {},
        db: [Object] },
     discriminators: undefined,
     '$appliedMethods': true,
     '$appliedHooks': true,
     _events: { init: [Function], save: [Function] },
     _eventsCount: 2,
     schema:
      Schema {
        obj: [Object],
        paths: [Object],
        aliases: {},
        subpaths: {},
        virtuals: [Object],
        singleNestedPaths: {},
        nested: {},
        inherits: {},
        callQueue: [Array],
        _indexes: [],
        methods: {},
        statics: {},
        tree: [Object],
        query: {},
        childSchemas: [],
        plugins: [Array],
        s: [Object],
        _userProvidedOptions: undefined,
        options: [Object],
        '$globalPluginsApplied': true },
     collection:
      NativeCollection {
        collection: [Object],
        opts: [Object],
        name: 'domains',
        collectionName: 'domains',
        conn: [Object],
        queue: [],
        buffer: false,
        emitter: [Object] },
     Query: { [Function] base: [Object] },
     '$__insertMany': [Function],
     insertMany: [Function],
     '$init': Promise { emitter: [Object], emitted: [Object], ended: false } } }
```

**Comment by freethewhat** [comment]
After testing heatmap and zone it appears there is an issue in all the query routes. It appears to work fine if you provide a date to it.

**Comment by freethewhat** [comment]
Relate pull request #24

**Comment by freethewhat** [comment]
Resolved
